const { builtinModules } = require("module")

const Characters = {

    1: "MARIO",
    2: "DONKEY_KONG",
    3: "LINK",
    4: "SAMUS",
    5: "DARK_SAMUS",
    6: "YOSHI",
    7: "KIRBY",
    8: "FOX",
    9: "PIKACHU",
    10: "LUIGI",
    11: "NESS",
    12: "CAPTAIN_FALCON",
    13: "JIGGLYPUFF",
    14: "PEACH",
    15: "DAISY",
    16: "BOWSER",
    17: "ICE_CLIMBERS",
    18: "SHEIK",
    19: "ZELDA",
    20: "DR_MARIO",
    21: "PICHU",
    22: "FALCO",
    23: "MARTH",
    24: "LUCINA",
    25: "YOUNG_LINK",
    26: "CHROM",
    27: "MR_GAME_AND_WATCH",
    28: "META_KNIGHT",
    29: "PIT",
    30: "DARK_PIT",
    31: "ZERO_SUIT_SAMUS",
    32: "WARIO",
    33: "SNAKE",
    34: "IKE",
    35: "SQUIRTLE",
    36: "IVYSAUR",
    37: "CHARIZARD",
    38: "DIDDY_KONG",
    39: "KING_DEDEDE",
    40: "OLIMAR",
    41: "LUCARIO",
    42: "ROB",
    43: "TOON_LINK",
    44: "WOLF",
    45: "VLLAGER",
    46: "MEGA_MAN",
    47: "WII_FIT_TRAINER",
    48: "ROSALINA_AND_LUMA",
    49: "LITTLE_MAC",
    50: "GRENINJA",
    51: "MII_BRAWLER",
    52: "MII_SWORDFIGHTER",
    53: "MII_GUNNER",
    54: "PAULETENA",
    55: "PAC_MAN",
    56: "ROBIN",
    57: "SHULK",
    58: "BOWSER_JR",
    59: "DUCK_HUNT",
    60: "RYU",
    61: "KEN",
    62: "CLOUD",
    63: "CORRIN",
    64: "BAYONETTA",
    65: "INKLING",
    66: "RIDLEY",
    67: "SIMON",
    68: "RICHTER",
    69: "KING_K_ROOL",
    70: "ISABELLE",
    71: "INCINEROAR",

    //DLC Fighters
    72: "PIRANHA_PLANT",
    73: "JOKER",
    74: "HERO",
    75: "BANJO_AND_KAZOOIE",
    76: "TERRY",
    77: "BYLETH",
    78: "MIN_MIN",
    79: "STEVE",
    80: "SEPHIROTH",
    81: "PYRA", 
    82: "MYTHRA",

}

builtinModules.exports = Characters;